import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import { env } from "process";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script
          async
          defer
          src={`https://maps.googleapis.com/maps/api/js?key=${env.NEXT_PUBLIC_REACT_APP_API_KEY}&libraries=places`}
        ></Script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
